name: Build LaTeX on any Docker image
description: |
  Parallel build of multiple files is supported, and you can use customized Docker image.
#   You can use not only latexmk but also pacdoc etc.

inputs:
  docker-image:
    description: Docker image published on Dockerhub that runs build.
    required: true

  build-files:
    description: A Line-separated list of paths of the TeX files to build.
    required: true

  build-entrypoint:
    description: The entrypoint of Docker container that runs build.
    required: false

  build-args:
    description: Extra arguments to run the build.
    required: false

branding:
  icon: file-text
  color: orange

runs:
  using: docker
  image: docker://satackey/action-latex:v3.0.0
  env:
    BUILD_IMAGE: ${{ inputs.docker-image }}
    BUILD_FILES: ${{ inputs.build-files }}
    BUILD_ENTRYPOINT: ${{ inputs.build-entrypoint }}
    BUILD_ARGS: ${{ inputs.build-args }}
